// Exports Foundry ABIs into typed `as const` modules for the app and keeper.
// Usage: node tools/export-abis.mjs  (after `forge build`)
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const names = [
  "IssuerRegistry", "ComplianceRegistry", "OfferingFactory", "OfferingEscrow",
  "FixedPriceOffering", "BatchAuction", "DutchAuction", "DeliveryVesting",
  "FeeCollector", "ProjectTokenHooks", "OracleAdapter", "Timelock",
];
const targets = [join(root, "../app/src/abi"), join(root, "../scripts/src/abi")];
let out = "// AUTO-GENERATED by contracts/tools/export-abis.mjs - do not edit.\n\n";
for (const n of names) {
  const art = JSON.parse(readFileSync(join(root, "out", `${n}.sol`, `${n}.json`), "utf8"));
  out += `export const ${n[0].toLowerCase() + n.slice(1)}Abi = ${JSON.stringify(art.abi)} as const;\n\n`;
}
out += `export const erc20Abi = ${JSON.stringify([
  { type: "function", name: "approve", stateMutability: "nonpayable", inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ type: "bool" }] },
  { type: "function", name: "allowance", stateMutability: "view", inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "balanceOf", stateMutability: "view", inputs: [{ name: "a", type: "address" }], outputs: [{ type: "uint256" }] },
  { type: "function", name: "decimals", stateMutability: "view", inputs: [], outputs: [{ type: "uint8" }] },
  { type: "function", name: "symbol", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
  { type: "function", name: "name", stateMutability: "view", inputs: [], outputs: [{ type: "string" }] },
])} as const;\n`;
for (const t of targets) {
  mkdirSync(t, { recursive: true });
  writeFileSync(join(t, "index.ts"), out);
}
console.log(`exported ${names.length} ABIs to ${targets.length} targets`);
